package_rename_config:
  android:
    app_name: Example # (String) The display name of the android app
    package_name: com.jemish54.template_test # (String) The package name of the android app

  ios:
    app_name: Example # (String) The display name of the ios app
    package_name: com.jemish54.template_test # (String) The product bundle identifier of the ios app

  linux:
    app_name: Example # (String) The display name of the linux app
    package_name: com.jemish54.template_test # (String) The package name of the linux app

  macos:
    app_name: Example # (String) The display name of the macos app
    package_name: com.jemish54.template_test # (String) The package name of the macos app

  web:
    app_name: Example # (String) The display name of the web app
    package_name: com.jemish54.template_test # (String) The package name of the web app

  windows:
    app_name: Example # (String) The display name of the windows app
    package_name: com.jemish54.template_test # (String) The package name of the windows app

flutter_launcher_icons:
  image_path: "assets/launcher.png"
  android: true
  ios: true

flutter_native_splash:
  color: "#000B25"
  image: "assets/launcher.png"
